Traceback (most recent call last):
  File "C:\Users\miaha\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\miaha\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import urllib.request as urllib2
#from urllib.request import urlopen
import json
import re
import urllib.parse
import pickle
from fa2 import ForceAtlas2
import collections
import powerlaw
import os
from nltk import FreqDist
from nltk.corpus import stopwords
from nltk import word_tokenize
import nltk
#from nltk.stem import WordNetLemmatizer
import collections
from IPython.display import Markdown as md
import seaborn as sns
from PIL import Image

#from scipy.interpolate import interp1d
#from pathlib import Path
from wordcloud import WordCloud
from nltk.corpus import PlaintextCorpusReader as pcr
#from nltk.corpus import PlaintextCorpusReader
#from nltk.tokenize import WordPunctTokenizer
#import string
import community
from importlib import reload 
reload(community)
#from math import isnan
#import random
from fa2 import ForceAtlas2
import random
from bokeh.io import output_notebook, show
from bokeh.models import Range1d, Circle, MultiLine, NodesAndLinkedEdges
from bokeh.plotting import from_networkx
#from bokeh.palettes import Blues8
import bokeh.plotting.figure as bokeh_figure

import gensim
import gensim.corpora as corpora
from gensim.models import CoherenceModel
from gensim.test.utils import common_corpus
import pyLDAvis
import pyLDAvis.gensim_models
import warnings


import re
from bs4 import BeautifulSoup
#from IPython.core.display import display, HTML
import requests


from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
%matplotlib inline 
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_4004/698552638.py[0m in [0;36m<module>[1;34m[0m
[0;32m     59[0m [1;33m[0m[0m
[0;32m     60[0m [1;33m[0m[0m
[1;32m---> 61[1;33m [1;32mfrom[0m [0mvaderSentiment[0m[1;33m.[0m[0mvaderSentiment[0m [1;32mimport[0m [0mSentimentIntensityAnalyzer[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     62[0m [0mget_ipython[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mrun_line_magic[0m[1;33m([0m[1;34m'matplotlib'[0m[1;33m,[0m [1;34m'inline'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'vaderSentiment'
ModuleNotFoundError: No module named 'vaderSentiment'

